name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
- name: Check out repository
  uses: actions/checkout@v4
  with:
    fetch-depth: 0

- name: Generate a changelog
  uses: orhun/git-cliff-action@v3
  with:
    config: cliff.toml
    args: --verbose
  env:
    OUTPUT: CHANGELOG.md
    GITHUB_REPO: ${{ github.repository }}
